language: node_js
node_js:
- lts/*
env:
  global:
    secure: cmaFYZUgmxe36Rr6cuMSQXi/Wi2MszdLCXxRLiw4UeVXEhapuVbCs/cbybndfr5idt23uRpQN5HU0LGgIL5ymfsCLclImrkEWgVdaI7VgZ2wpb9zuPPyWaw7zXLG/TVaX5/28OSb/vCQEwAJoU+RWt9jWa4qysESob2T/NwtVO0kkk10DyGhIFGuJWWJUBB9AXF/H0Nw1lEU5I3BqnzLURN0Wopol2PINnQVtMMmifCJ0w4g5Br0+OyExUwS50KpwlOCPRz0SUAgweP1VRjOrx5RV3VJmfDtqth3URMf6vMmrh0KmIDQpZnqgyW1SArLqDZdD2vrY1ypOerlt0ey+6Ngo871j5tfOM3D4RNcLJ4eJxM5iB2m1bXDCqnaa37b8h4mqubUDq6VApqRkUFT+ft28oLpV1RGHb4G1eNtEXmoCsza2jHvoQcK2kQC3mbdHopEAX8Q4xR3/fi70g4oJOr6BbJNKaQP5rY9Yi+IB7qvMFX4n+AGoP4J0LhM8ebB6tCxBGNmaIEgsbTle/CCX3bNOaXNcN6rmAeOucW11qSaHUwx3kI+2hXLUAKqjnUBo4Ri5ExTH5deY5GzhDL1yRXclv48Q7vdUnWnCZj1+zUhBKgKl4UkHilBYly/uCT2+qVp0E8PK8sPTIOhbTYp2cumXNDzk8jUYw0uMSXrmu0=
