language: node_js
node_js:
- lts/*
env:
  global:
  - secure: Rl2LfPlVos5YnauB/RWn8YVjHJHClkW8B3v9NDSMlof89OHtpJ4c0hcxMyrs7M+DycOYDysybNFSXO7OWX+M9Lfb/IL96ouf4m5B9i1XpvC5m/2qkdE2c/hn86RumqRgKPcv9Izy7oyv0+5lUa31i8852KoqZxOaAgIhA0a1GulLwSfMhwcg1QdtCm91Cr/nrF3MiXoqo4/011pyWQp+bobfsgm7eabZeiPUg0oMzr5hADUFleu0ijoNBupYUpF45oxZNAk3XZsC2CspTHHI3LgfYrfFGmNcq885kR+ezwp57uHk3SiGBoYtwQFeymJz3X5XvQZRV+MQvdTF0n6eCbHp5xE3mnNNGMNrdL83SbSRxb203jBkvcXfUEd7zlB+BPKk0YQkXhQElwj3GMDy1xJAj120MKjHOkfXN50Fu/W8oDZUuWQ+ZtOSjb0Zj8bEcVrxIZWNWb4Cal5kORWBoH21vDuGl3WOWNtlBpNBfBWNDOuFJj3eZgye0TSDx4HqgA6E0EoSO781XrWRjP8GbY6Z5zjYKyuBF2O5aOPn4hjSYdKfYA7rDFzdk7acc9pbA5CaBRMtS+LDVA/nIEK7TeUfLqLsXU9jIZLC1D86X5mg2mtwe5JYQA1yNXcwYbCGsN1fZegKTBLqkZKpYIa6CkTsmSZhv8/3fiLWzr8UB64=
